### PR TITLE
Feature/device control spi support

### PR DESCRIPTION
**Pull request by shuchitak**
https://github.com/xmos/sw_xvf3800/issues/34

### CODE REVIEW

**Comment by xmos-jmccarthy** [comment]
Will USB device control be affected by these changes?

**Comment by shuchitak** [comment]
> Will USB device control be affected by these changes?
Hmm, good point. I haven't changed any API, so nothing should fail. However, I've made changes to the control_ret_t enum, so that might be a problem. Are there any host apps that use the device control? I didn't find any in the xcore_sdk. If there are, they might need to be changed to ensure that they are checking for the correct error codes for cases such as the device asking the host to retry a read command since its not ready with a response yet. For this particular case, earlier the retry error code was 1, while its now 64 (SERVICER_COMMAND_RETRY) since it's technically a servicer error and should be in the space reserved for servicer errors in the control_ret_t enum.

**Comment by xmos-jmccarthy** [comment]
I don't believe that there are any usb device control apps that depend on the response command yet.  STLP was the only one, but these have been removed.

There is an example for device control in the SDK,
https://github.com/xmos/xcore_sdk/blob/3e2b44f8ae2004abe8b5761532f07233c5c6d16c/examples/freertos/device_control/src/main.c#L31-L64

Since this example focuses on use of the driver as a whole, not on the particular control flow built on top of it, it does not appear to be affected.

**Review by xmos-jmccarthy — APPROVED** [review]
Rubber stamped.

Please open a new issue to expand the example/freertos/device_control example application to also contain the spi slave.

**Pull request merged**
