### PR TITLE
Added datapartition_mkimage tool

### PR DESCRIPTION
**Pull request by jcarrier-xmos**

### CODE REVIEW

**Comment by jcarrier-xmos** [comment]
Small note, the input filenames that are emitted to the table are 1:1 with what the command line arg specified. If there is a desire to drop the path content of the argument (potentially causing ambiguity if multiple sources files have the same name), I can do that.

Also, another side thought I have had in the past and it popped up again, was whether or not I should try to standardize on the exit codes (i.e. use a common enum, adopt `errno.h`, etc).

**Comment by keithm-xmos** [comment]
I have verified that this build on an Intel Mac.  I do see this warning which might be worrisome.  

```
/Users/xxxxxxx/repos/xcore_sdk/modules/rtos/tools/datapartition_mkimage/datapartition_mkimage.c:24:9: warning: 'FREAD' macro redefined [-Wmacro-redefined]
#define FREAD(buf, buf_size, elem_size, elem_cnt, file)                        \
        ^
/Library/Developer/CommandLineTools/SDKs/MacOSX13.1.sdk/usr/include/sys/fcntl.h:110:9: note: previous definition is here
#define FREAD           0x00000001
```

**Comment by keithm-xmos** [comment]
We should add a CI job to build this app.

See https://github.com/xmos/xcore_sdk/blob/main/tools/ci/build_host_apps.sh for how we have the xcore_sdk build the host apps.  A script like this will need  be added to this repo.  

See https://github.com/xmos/xcore_sdk/blob/main/.github/workflows/ci_examples.yml#L31-L52 for the GitHub Action job.

**Comment by keithm-xmos** [comment]
Also, a component/unit test should also be added.  Given it is not a system test, it may want to live in `/tools/datapartition_mkimage/test`.  And, we can add a CI step to run the test after the host build.

**Comment by jcarrier-xmos** [comment]
> I have verified that this build on an Intel Mac. I do see this warning which might be worrisome.

OK, thanks for checking. That #include is only needed for the _O_BINARY flag to set the stdin to binary mode. So I moved the #include into the #ifdef _WIN32 section below which is the only use-case for it in this app.

If there is ever a reason to include that header on other platforms, renaming the #defines at the top of this file to F_READ/F_OPEN/etc or something should be sufficient.

> A script like this will need be added to this repo.
> Also, a component/unit test should also be added.

I will start working on these items.

**Comment by jcarrier-xmos** [comment]
Fixed a typo in the help string

**Review by keithm-xmos — APPROVED** [review]

**Pull request merged**
