### PR TITLE
Adding libusb binary built for mac arm64

### PR DESCRIPTION
**Pull request by uvvpavel**
Part of [issue 90 in host_xvf_control](https://github.com/xmos/host_xvf_control/issues/90).

### CODE REVIEW

**Comment by xmos-jmccarthy** [comment]
Swapping reviewer to @keithm-xmos to verify on MacOS

**Comment by keithm-xmos** [comment]
I believe we may also need to updated this so the correct library is added to the LINK_LIBS: 

https://github.com/xmos/fwk_rtos/blob/develop/modules/sw_services/device_control/CMakeLists.txt#L35-L38

**Comment by keithm-xmos** [comment]
Also, at one point it was thought that it might be better to require libusb install from Homebrew.  I don't have a strong opinion.  See: https://github.com/xmos/fwk_rtos/issues/94

**Review by keithm-xmos — APPROVED** [review]
Jenkins test is failing in completely unrelated manner.  I'm OK merging this PR with the failing test.

**Pull request merged**
