### PR TITLE
add disclaimer to legal.rst

### PR DESCRIPTION
**Pull request by BrennanGit**

### CODE REVIEW

**Review by lucianomartin — APPROVED** [review]
Looks good!

**Comment by BrennanGit** [comment]
although I'm still not sure if this should be in the top-level index instead.

eg:
image

here, the copyright and disclaimer is duplicated in each section.

Bare in mind that it is appended automatically at the end of each of the pdfs so we only need to add it for html.

Maybe even this little block covers our needs completely?
image

**Review by mbanth — APPROVED** [review]
@tomblackie-xmos is the person that decides where we need licence, copyright and disclaimer statements.  @BrennanGit, please direct your questions about where they should appear in the HTML documentation to him.  This change is suitabel from my point of view.

**Comment by tomblackie-xmos** [comment]
> @tomblackie-xmos is the person that decides where we need licence, copyright and disclaimer statements. @BrennanGit, please direct your questions about where they should appear in the HTML documentation to him. This change is suitabel from my point of view.

I've had a look at the build artifact and it looks OK - I understand that it is duplicated on the LHS menu, but these are two separate docs so it is not totally illogical. Please go ahead

**Pull request merged**
